In [1]:
import matplotlib.pyplot as plt
import numpy as np

In [9]:
a = np.array([
    [12,
    34,
    45],[
    56,
    67,
    89]])


In [11]:
a

array([[12, 34, 45],
       [56, 67, 89]])

In [13]:
a.ndim

2

In [21]:
print(a[1, 2])

89


In [23]:
a.shape

(2, 3)

In [25]:
a.size

6

In [27]:
Arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [29]:
Arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [31]:
Arr.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [33]:
Arr.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [35]:
Arr.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])